---
- name: Install and Start nginx
  hosts: all
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
